### PR TITLE
B-04004 - Version of refactor compatible with current dna 

### PR DESCRIPTION
**Pull request by robbiecarlton**

### CODE REVIEW

**Review by zippy — APPROVED** [review]
Looks good except for the message count stuff!

**Comment by JettTech** [comment]
FYI: I noticed that when running the tests with this version, we get an error stating `Error: mock callZome called with unknown fnName: signal_chatters`.  Looks like the `signal_specific_chatters` needs to become `signal_chatters` in the store mocks.

**Review by JettTech — COMMENTED** [review]
@robbiecarlton FYI: I noticed that when running the tests with this version, we get an error stating `Error: mock callZome called with unknown fnName: signal_chatters`.  Looks like the `signal_specific_chatters` needs to become `signal_chatters` in the store mocks.

**Comment by zippy** [comment]
> @robbiecarlton FYI: I noticed that when running the tests with this version, we get an error stating `Error: mock callZome called with unknown fnName: signal_chatters`. Looks like the `signal_specific_chatters` needs to become `signal_chatters` in the store mocks.

good catch

**Comment by robbiecarlton** [comment]
@JettTech - thanks Lisa, fixed the broken test.

**Review by JettTech — APPROVED** [review]
LGTM

**Comment by zippy** [comment]
obsolete

**Pull request closed without merging**
