### PR TITLE
Comment out signals

### PR DESCRIPTION
**Pull request by JettTech**
### Updates:
 - comments out signals to avoid extra noise (while signals are not yet merged upstream)

### CODE REVIEW

**Comment by alastairong** [comment]
@JettTech This looks like it only silences received signals. Is there an easy way to stop signals from getting sent as well?

**Comment by JettTech** [comment]
@alastairong - We can change the DNA code to not send them.  The UI is on the receiving end though, so it can only manage what it listens to and handles or does not.

**Comment by alastairong** [comment]
Nevermind then. Was looking for UI changes only.

**Comment by alastairong** [comment]
No longer needed as now testing signals

**Pull request closed without merging**
